### ISSUE TITLE
Game softlocking completely unable to use MenuUI

### ISSUE THREAD

**Issue by ghost** [chrislee0419/EnhancedSearchAndFilters#10]
I get this issue if i just search normally with this mod when combined with SongBrowser, I dont know if it is this mod or SongBrowser, but if you could try to resolve this with the Author of SongBrowser, it would be amazing,

**Comment by chrislee0419** [comment]
Can you send me a copy of your log? You can find it at `Beat Saber\Logs\_latest.log`.

**Comment by Flewrider** [comment]
Happens to me almost every time I try to search something. Worked for a while in conjunction with songbrowser then it started to crash. Do not know if it was after an update of one of the two mods. 
Will attach a log the next time it happens + screenshot of what it looks like.

**Comment by chrislee0419** [comment]
I think I might know what it is. Are either of you using the mod SongPlayHistory? There was an issue I fixed some days ago where SongPlayHistory would cause the UI to softlock immediately after selecting a song in this mod's Search menu.

It was 'fixed' in commit 4626568, but I have yet to build it for release since it hasn't been tested yet.
 
If this sounds like this is the same issue that either of you are experiencing, let me know and I could compile it for you to see if it fixes it.

**Comment by thezeagar** [comment]
That sounds exactly like the bug I was coming here to report..  I'll remove SongPlayHistory for now, and I'll gladly test the fix as well if you compile it.

**Comment by Flewrider** [comment]
yep using songplayhistory as well. Also added it recently when the issues started to appear so sounds like the solution. DM the test version on discord @Flewrider9406

**Comment by chrislee0419** [comment]
Here's a copy of the mod with the fix included.

[esaf.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/4223599/esaf.zip)

**Comment by thezeagar** [comment]
Unfortunately didn't seem to work for me, but instead was kinda worse. With the fixed version + songplayhistory the whole game locks up instead of just the menu locking up.  Either way I have to force close the game. Still only happens when I try to search with songplayhistory installed. Tried it a few times, then removed songplayhistory again.

**Comment by chrislee0419** [comment]
@thezeagar, any chance you still have the logs for when that happened?

**Comment by thezeagar** [comment]
Sorry, haven't had time to play the past week, but I just boot it up with fpfc real quick to get logs for it.

It happens every time I try to click on a search result when using songplayhistory and the test version you provided.

I deleted my output_log file, started the game, performed a search, clicked on a result, and the game stopped responding and had to be force closed. So this output_log only contains data from a relevant run.

Let me know if I can provide anything else to help.

[output_log.txt](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/4259478/output_log.txt)

**Comment by chrislee0419** [comment]
Okay, so, I was finally able to finish up some other stuff and find some time to look into this and test the fix myself.

[esaf.zip](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/4259678/esaf.zip)

The attached zip contains a modified version of the mod with an ACTUAL fix, as opposed to breaking more stuff.

If this fixes the problem for at least one other person (and I'm assuming everyone here is referring to the same problem), I'll just consider this issue finished and close this.

**Comment by thezeagar** [comment]
That fixed it for me. Thank you!

**Comment by chrislee0419** [comment]
@thezeagar, thanks for trying it out and reporting it!

**Comment by swift-kim** [comment]
I'm the author of SongPlayHistory and just ran into this. Sorry for the inconvenience and I'll also check if this can be fixed from my side just in case.

**Comment by chrislee0419** [comment]
@swift-kim Hey, no problem!

It was my fault for coding it in a way that doesn't take other mods into account.

The fix I have works and I'm probably going to refactor that code anyways. There's another method that BeatSaverDownloader uses for instantiating the song details view before any mods are able to modify it, so it's likely I'll do that instead at some point.
