### ISSUE TITLE
[Feature Request] Ability to apply search as a filter

### ISSUE THREAD

**Issue by Kylemc1413** [chrislee0419/EnhancedSearchAndFilters#15]
Currently if I want to search for all songs by a mapper or similar, I have to go back to the search menu and redo last search every time I want to select another song from the search, it would be convenient if there were a way to have the current search results applied to the current level collection like the results of a filter.

**Comment by chrislee0419** [comment]
kyle pog

Sure, I'll take a look at that once I'm finished some other stuff.
