### ISSUE TITLE
Issue with Clicking Solo Button

### ISSUE THREAD

**Issue by Rayn322** [chrislee0419/EnhancedSearchAndFilters#19]
**Latest Log File:**
Before you do anything else, attach a copy of the '_latest.log' file from the 'Beat Saber\Logs\' folder.
[_latest.log](https://github.com/chrislee0419/EnhancedSearchAndFilters/files/4679125/_latest.log)

**Description:**
When clicking solo and then going back to the main menu, I'm not able to click solo again. Nothing happens.

**Steps To Reproduce**
(Optional) If it is a complicated/complex issue, list the steps to reproduce the bug with as much detail as possible. Otherwise, feel free to delete this section.
1. Click Solo
2. Click Back
3. Click solo.
4. Nothing happens.

**Expected Behaviour:**
Clicking solo brings me to song selection.

**Comment by chrislee0419** [comment]
Thanks for reporting! From what I see in the log, it looks like it's an easy one liner null check fix. It appears that this occurs when the filter feature is disabled when also using SongBrowser.

By the way, from the log, it looks like you've disabled both the search and filter features of this mod. That pretty much has the same effect as disabling this mod. In that case, assuming you no longer use ESAF, why not just remove the mod?

**Comment by Rayn322** [comment]
Whoops! I didn’t mean to disable it. My mod settings have been deciding not to save for whatever reason so I’ll look at that.
