### ISSUE TITLE
Restore last sorting after game restart

### ISSUE THREAD

**Issue by Kakifrucht** [chrislee0419/EnhancedSearchAndFilters#22]
Great mod, I do prefer it over SongBrowser. 
I'm missing one very minor feature though, can you save which sorting/filter was used last and restore it after a game restart?

Thanks!

**Comment by chrislee0419** [comment]
Hey Kakifrucht,

Sure, I'll take a look into doing that. It shouldn't be too difficult, but it may take some time, since I'm reworking the sort stuff right now.

**Comment by Kakifrucht** [comment]
closing because abandoned / replaced
