### ISSUE TITLE
Suggestion: Filter unplayed songs

### ISSUE THREAD

**Issue by jsmars** [chrislee0419/EnhancedSearchAndFilters#8]
Currently you can filter for songs that you have played, which is great, but when you want to try out new songs, it would be so useful to be able to choose to filter songs that you have **not** played.

Edit: Also being able to sort by your own pp for songs would also be a great addition, to find which songs you can improve on.

Would be really appreciated. Thanks for a great mod!

**Comment by chrislee0419** [comment]
Hey, thanks for the suggestions.


Currently, you can already filter by songs that you have not yet played. In the "Player Stats" filter, there is a setting called "Songs Completed At Least Once", which has two options.

The "Keep Completed" option will filter out all songs that you have completed at least once, on at least one difficulty.

The **"Has Never Completed" option will filter out songs that you have never finished successfully (on any difficulty).** This is the option you should use to find songs that you have not played (unless you also want to filter out songs that you have attempted but never finished, in which case, there isn't any filter for that but could be created).


Also, regarding the ability to sort by your own PP, unfortunately, I won't be able to do that. ScoreSaber is essentially a black box, so I don't have access to its data to do that.

**Comment by jsmars** [comment]
Thanks for the quick response. My bad on not finding the "songs completed at least once", the wording of the filter there made me think that it was only songs that you've played, so I only clicked the filter once to see and missed the second option. Thanks for that! An additional one for those also never played at all would also be helpful but not as vital as the one already there.

Too bad about the scoresaber scores, would have been very helpful to have a filter for that. 

Anyway, no real issues to attend to then so I will close this for now. Thanks again for a great mod!
